### PR TITLE
Add dependency to cmake_modules to build on indigo

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by fairlight1337** [comment]
Thanks!

**Comment by airballking** [comment]
Merging this fix for building under indigo into the ```hydro-devel``` branch seems like a mistake to me. @fairlight1337 @garaemon Is this working under hydro?

Also: We already have this fix in the ```master``` branch which is intended for the most recent developments. See this pull request code-iai/snap_map_icp#4 from November.

**Comment by fairlight1337** [comment]
@airballking - Works for me, yeah, tried it just now. Did any problems come up?

**Comment by fairlight1337** [comment]
But of course, you're right, there's another pull request. Didn't see that one.

**Comment by airballking** [comment]
Then all is fine. Thanks for checking!

**Pull request merged**
